// Generated by https://quicktype.io

export interface ConsultaRtn {
  data:      Data;
  isSuccess: boolean;
  message:   null;
}

export interface Data {
  obligadoTributario: ObligadoTributario;
}

export interface ObligadoTributario {
  rtn:                  string;
  nombre:               string;
  segundoNombre:        string;
  primerApellido:       string;
  segundoApellido:      string;
  nombreComercial:      string;
  barrio:               string;
  calleAvenida:         string;
  bloque:               string;
  sector:               string;
  numeroCasa:           string;
  departamento:         Departamento;
  actividadPrimaria:    ActividadAria;
  actividadSecundaria:  ActividadAria;
  fechaInicioActividad: string;
}

export interface ActividadAria {
  actividadId: string;
  descripcion: string;
}

export interface Departamento {
  departamentoId: number;
  descripcion:    string;
}
