// Generated by https://quicktype.io

export interface VentasBrutas {
  data:      Data;
  isSuccess: boolean;
  message:   null;
}

export interface Data {
  ventasBrutas: { [key: string]: number };
}
